baseURL: https://log.mhaziqrk.uk/
languageCode: en-us
title: Mhaziqrk Log
theme : PaperMod 
defaultContentLanguage: ms
copyright : "Hak Milik Mhaziqrk."
params : 
    env: production
    disableScrollToTop: false

    keywords: [Blog, Portfolio, Tech, IT]
    ShowCodeCopyButtons : true
    ShowShareButtons: true
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    author: Haziq Rohaizan
    fuseOpts:
            isCaseSensitive: false
            shouldSort: true
            location: 0
            distance: 1000
            threshold: 0.4
            minMatchCharLength: 0
            keys: ["title", "permalink", "summary", "content"]

    socialIcons: # optional
        - name: "Instagram"
          url: "http://ig.mhaziqrk.uk"
        - name: "Github"
          url: "https://github.com/mhrk04"
        - name: "Twitter"
          url: "https://twitter.com/haziqrohaizan" 
        - name: "telegram"
          url: "https://t.me/mhrk04"
         
    cover :
      linkFullImages : true
      responsiveImages: false


    profileMode:
        enabled: true
        title: "Mhaziqrk Log" # optional default will be site title
        subtitle: "Just contain daily log of my work and personal note.\n
        This website uses two languages, English and Malay🇲🇾.
        Everyday learn new technology!"
        imageUrl: "favicon.ico" # optional
        # imageTitle: "<title of image as alt>" # optional
        # imageWidth: 120 # custom size
        # imageHeight: 120 # custom size
        buttons:
            - name: Posts
              url: posts
        assets:
              # disableHLJS: true # to disable highlight.js
              # disableFingerprinting: true
              favicon: "/favicon.ico"
              favicon16x16: "/favicon.ico"
              favicon32x32: "</favicon.ico"
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: Archives
      name: archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
    - identifier: posts
      name: posts
      url: /posts/
      weight: 40
